repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.15
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      types_or: [python, pyi, jupyter]
    - id: ruff-format
